# Generated by Django 4.2.1 on 2023-09-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compras',
            old_name='costo',
            new_name='total_compra',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='total',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_factura',
            field=models.DateField(blank=True, null=True),
        ),
    ]
