# Generated by Django 4.2.1 on 2023-09-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_rename_servicio_compras_servicios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='nombre_cliente',
            new_name='cliente',
        ),
    ]
