# Generated by Django 4.2.1 on 2023-09-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_rename_nombre_cliente_pedido_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.BooleanField(default=True),
        ),
    ]
