# Generated by Django 4.2.1 on 2023-09-14 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_alter_pedido_estado_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compras',
            old_name='iva',
            new_name='descuento',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='iva',
            new_name='descuento',
        ),
    ]
