# Generated by Django 4.2.1 on 2023-09-14 22:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0006_rename_iva_compras_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_factura',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
