# Generated by Django 4.2.1 on 2023-09-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0007_alter_pedido_fecha_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_factura',
            field=models.DateField(),
        ),
    ]
