# Generated by Django 4.2.1 on 2023-09-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='direccion_profesor',
            field=models.CharField(max_length=40),
        ),
    ]
