# Generated by Django 4.2.1 on 2023-07-17 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('apellido_cliente', models.CharField(max_length=70)),
                ('telefono_cliente', models.CharField(max_length=15)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('direccion_cliente', models.TextField()),
                ('numero_documento', models.BigIntegerField()),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profesor.tipo_documento')),
            ],
        ),
    ]
