# Generated by Django 4.2.1 on 2023-09-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion_cliente',
            field=models.CharField(max_length=40),
        ),
    ]
