# Generated by Django 4.2.1 on 2023-09-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_cliente_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono_cliente',
            field=models.BigIntegerField(),
        ),
    ]
